// The Proposal generated by the AI
export interface PropuestaLexIA {
    engineVersion: string;
    evidenceVersion: string;
    indiceVersion: string;
    expedienteId: string;
    consecutivo: number;
    investigationReportSnapshot: any;
}

// Action taken by human
export type HumanAction = 'APROBAR' | 'MODIFICAR' | 'RECHAZAR' | 'POSPONER';

// The final Human Decision structure
export interface HumanDecisionData {
    expedienteId: string;
    consecutivo: number;
    accion: HumanAction;
    observaciones: string;
}

// The core Event representing a Human Decision (Append-Only Event Sourcing style)
export interface DecisionEvent {
    eventId: string;
    documentId: string;
    timestamp: string;
    userId: string;
    
    propuestaLexia: PropuestaLexIA;
    decisionFuncionario: HumanDecisionData;
    
    // Cryptographic hash of this event to guarantee immutability/auditability
    hash: string;
}

export interface IDecisionRepository {
    appendEvent(event: DecisionEvent): Promise<void>;
    getEvents(documentId: string): Promise<DecisionEvent[]>;
}
