using System.Text;
using System.Threading;
using System.Threading.Tasks;
using LexIA.Application.Presentation.Profiles;
using LexIA.Application.Presentation.Prompts;

namespace LexIA.Application.Presentation.Generation;

public sealed class DeterministicExplanationGenerator : IExplanationGenerator
{
    public Task<string> GenerateAsync(PromptModel prompt, IExplanationProfile profile, CancellationToken cancellationToken = default)
    {
        // This is a deterministic generator for E2E tests and local offline development.
        // In a real scenario, this would be the OpenAIExplanationGenerator calling the API.
        
        var sb = new StringBuilder();
        
        sb.AppendLine($"[GENERATED BY DETERMINISTIC ENGINE - PROFILE: {profile.ProfileId}]");
        sb.AppendLine();
        
        sb.AppendLine($"El resultado del análisis ha sido: {prompt.Outcome}");
        sb.AppendLine($"La base legal aplicada es: {prompt.LegalReferences}");
        
        sb.AppendLine("Línea de tiempo del caso:");
        sb.AppendLine(prompt.Timeline);

        // Simulating the rule "ForbiddenClaimRule" by NOT including forbidden claims
        // and including required disclosures.
        
        sb.AppendLine();
        sb.AppendLine("Nota legal: Esta decisión puede ser apelada en los plazos establecidos por la ley.");

        return Task.FromResult(sb.ToString());
    }
}
